from models import db, User, Post, Tag
from app import app

# db.drop_all()
db.create_all()

User.query.delete()

philip = User(first_name='Philip', last_name='Harmon')
jessica = User(first_name='Jessica', last_name='Culpepper')
herbert = User(first_name='Herbert', last_name='Van Nostren')
abercrombie = User(first_name='Abercrombie', last_name='Fitzsimmons')
claus = User(first_name='Claus', last_name='Von Struddel')
heinz = User(first_name='Heinz', last_name='Von Struddel')
fawn = User(first_name='Fawn', last_name='Liebowitz')
giusseppi = User(first_name='Giusseppi', last_name='Friedlichson')
abigail = User(first_name='Abigail', last_name='Gerschwin')
miles = User(first_name='Miles Stanley', last_name='Batiste')
gertrude = User(first_name='Gertrude', last_name='Holliwell')
myron = User(first_name='Myron', last_name='Lutzman')
fernando = User(first_name='Fernando', last_name='Guetenburg')
gwynnievre = User(first_name='Gwynnievre', last_name="O'Callahan")
miranda = User(first_name='Miranda', last_name='Fitzpatrick')
bartholomew = User(first_name='Bartholomew', last_name='Jones')
josiah = User(first_name='Josiah', last_name='Fitzhume')
appleby = User(first_name='Appleby', last_name='Steinbeck')



Post.query.delete()

post1 = Post(title='Test', content='This is a test', user_id=1)
post2 = Post(title='Quite the site', content='I love this site. You guys rock!', user_id=1)
post3 = Post(title='Stop and smell the roses', content='Some sage advice...', user_id=14)
post4 = Post(title='When in rome...', content='When in Rome, roam!', user_id=4)
post5 = Post(title='All I want for Christmas', content='Is my two front teeth!', user_id=20)
post6 = Post(title='Tomorrow and tomorrow and tomorrow', content='Creeps along at this petty pace...', user_id=19)
post7 = Post(title='Time to play the lottery', content="It's getting quite large", user_id=8)
post8 = Post(title='I want to learn piano', content="It's about time to learn an instrument!", user_id=12)
post9 = Post(title='I love dogs', content='And dogs love me!', user_id=13)
post10 = Post(title='I love cats!', content='And cats love me!', user_id=17)
post11 = Post(title='Calling all Phish heads', content='Hi!', user_id=1)
post12 = Post(title="What's the deal with airplane peanuts?", content='I mean, come on!', user_id=15)
post13 = Post(title='I love movies!', content='And they love me!', user_id=20)
post14 = Post(title='Animal House', content="I didn't die in the movie. That was fiction!", user_id=11)
post15 = Post(title='Somebody help!', content="I'm bored!", user_id=16)
post16 = Post(title='The road less traveled', content='Is less traveled for a reason', user_id=18)
post17 = Post(title='Restaurant recommendations', content="Where's a good place to eat?", user_id=22)
post18 = Post(title='Headed to Des Moines', content='Why???', user_id=7)
post19 = Post(title='My brother is great!', content='I love him!', user_id=9)
post20 = Post(title="My brother's a duffus!", content='What a maroon!', user_id=10)

tags1 = Tag(name='Jessica Culpepper')
tags2 = Tag(name='Herbert Von Nostren')
tags3 = Tag(name='Abercrombie Fitzsimmons')
tags4 = Tag(name='Claus Von Struddel')
tags5 = Tag(name='Heinz Von Struddel')
tags6 = Tag(name='Fawn Liebowitz')
tags7 = Tag(name='Giusseppi Friedlichson')
tags8 = Tag(name='Abigail Gerschwin')
tags9 = Tag(name='Miles Stanley Batiste')
tags10 = Tag(name='Gertrude Holliwell')
tags11 = Tag(name='Myron Lutzman')
tags12 = Tag(name='Fernando Guetenburg')
tags13 = Tag(name="Gwynnievre O'Callahan")
tags14 = Tag(name='Miranda Fitzpatrick')
tags15 = Tag(name='Bartholomew Jones')
tags16 = Tag(name='Josiah Fitzhume')
tags17 = Tag(name='Appleby Steinbeck')
tags18 = Tag(name='Jessica Culpepper')
tags19 = Tag(name='Jessica Culpepper')
tags20 = Tag(name='Jessica Culpepper')


db.session.add_all([philip, jessica, herbert, abercrombie, claus, heinz, fawn, giusseppi, abigail, miles, gertrude, myron, fernando, gwynnievre, miranda, bartholomew, josiah, appleby])
db.session.commit()

db.session.add_all([post1, post2, post3, post4, post5, post6, post7, post8, post9, post10, post11, post12, post13, post14, post15, post16, post17, post18, post19, post20])
db.session.commit()

db.session.add_all([tags1, tags2, tags3, tags4, tags5, tags6, tags7, tags8, tags9, tags10, tags11, tags12, tags13, tags14, tags15, tags16, tags17, tags18, tags19, tags20])
db.session.commit()
